# Generated by Django 4.2.7 on 2023-11-23 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Notice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reg_date", models.DateTimeField(auto_now_add=True)),
                ("notice", models.TextField()),
                ("week", models.IntegerField(default=0)),
            ],
        ),
    ]
