# Generated by Django 4.2.7 on 2023-11-18 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0003_card_ornament_x_card_ornament_y_alter_card_week"),
    ]

    operations = [
        migrations.AlterField(
            model_name="card",
            name="ornament_x",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="card",
            name="ornament_y",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
