# Generated by Django 4.2.7 on 2023-11-19 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0004_alter_card_ornament_x_alter_card_ornament_y"),
    ]

    operations = [
        migrations.AddField(
            model_name="card",
            name="img_path",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
